services:
  db:
    image: mongo:4.4  # Imagen de MongoDB
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data  # Mapea la carpeta `data` al contenedor
    command: mongod  # Solo inicia MongoDB
    healthcheck:
      test: ["CMD", "mongo", "--host", "localhost", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_initializer:
    image: mongo:4.4
    depends_on:
      db:
        condition: service_healthy  # Espera a que 'db' esté saludable
    volumes:
      - ./data:/data
    entrypoint: bash -c "/data/init-mongo.sh"  # Ejecuta el script de inicialización y luego se cierra

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/talent_skill
    ports:
      - "3000:3000"
    command: npm start
